"""Add gender to user

Revision ID: ddd472e4a9cd
Revises: 002
Create Date: 2026-09-27 08:15:40.324333
"""
from alembic import op
import sqlalchemy as sa


revision = 'ddd472e4a9cd'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('videos_drive_file_id_key'), 'videos', type_='unique')
    op.drop_index(op.f('ix_videos_drive_file_id'), table_name='videos')
    op.create_index(op.f('ix_videos_drive_file_id'), 'videos', ['drive_file_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_drive_file_id'), table_name='videos')
    op.create_index(op.f('ix_videos_drive_file_id'), 'videos', ['drive_file_id'], unique=False)
    op.create_unique_constraint(op.f('videos_drive_file_id_key'), 'videos', ['drive_file_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
